app = "aleabbeybeercalculator"
primary_region = "fra"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "off"
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    soft_limit = 25
    hard_limit = 50

  [[http_service.checks]]
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "20s"
    method = "GET"
    path = "/"
